var table1 = prompt("Type 1 Table no. ", 11);
var m1 = table1 * 1;
document.write(table1 + " x 1 = " + m1);
var m2 = table1 * 2;
document.write("<br />" + table1 + " x 2 = " + m2);
var m3 = table1 * 3;
document.write("<br />" + table1 + " x 2 = " + m3);
var m4 = table1 * 4;
document.write("<br />" + table1 + " x 2 = " + m4);
var m5 = table1 * 5;
document.write("<br />" + table1 + " x 2 = " + m5);
var m6 = table1 * 6;
document.write("<br />" + table1 + " x 2 = " + m6);
var m7 = table1 * 7;
document.write("<br />" + table1 + " x 2 = " + m7);
var m8 = table1 * 8;
document.write("<br />" + table1 + " x 2 = " + m8);
var m9 = table1 * 9;
document.write("<br />" + table1 + " x 2 = " + m9);
var m10 = table1 * 10;
document.write("<br />" + table1 + " x 2 = " + m10);

document.write("<br />Sum of : " + table1 + "["+(m1+m2+m3+m4+m5+m6+m7+m8+m9+m10)+"]");
